# Generated by Django 4.1.13 on 2023-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=40)),
                ('age', models.IntegerField(max_length=40)),
                ('pred', models.CharField(max_length=40)),
            ],
        ),
    ]
