# Generated by Django 4.1.13 on 2024-01-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bald', '0002_alter_human_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='skin',
            field=models.CharField(default='default_value', max_length=40),
        ),
    ]
